In [2]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


data = pd.read_csv('car.data')
print(data.head())



  buying  maint door persons lug_boot safety  class
0  vhigh  vhigh    2       2    small    low  unacc
1  vhigh  vhigh    2       2    small    med  unacc
2  vhigh  vhigh    2       2    small   high  unacc
3  vhigh  vhigh    2       2      med    low  unacc
4  vhigh  vhigh    2       2      med    med  unacc


In [15]:
X =  data[[
    'buying',
    'maint',
    'safety'
]].values

y = data[['class']]

print(X)


[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]


In [16]:
# Converting the data using label encoder 

#X
le = LabelEncoder()

for i in range(len(X[0])):
    X[:, i] = le.fit_transform(X[:, i])

print(X)


#Y
label_mapping = {
    'unacc': 0,
    'acc': 1,
    'good':2,
    'vgood':3
}

y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


C:\Users\NDUKWE\AppData\Local\Temp\ipykernel_9036\2479781831.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


In [17]:
#creating our models

knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

knn.fit(X_train, y_train)

predictions = knn.predict(X_test)

accuracy = metrics.accuracy_score(y_test, predictions)
print('predictions', predictions)
print('accuracy', accuracy)

c:\Users\NDUKWE\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


predictions [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0
 0 1 0 0 3 0 0 0 0 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
 1 3 0 2 0 0 1 0 0 1 3 0 0 0 1 0 0 0 0 0 3 1 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 2 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 3 0 0 0 0 1 0 0 2 0 0 3 0
 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 2 0 1 1 0 0 0 1 0 3 0 1 0 1 0 1 0 1 0 3 3 0
 0 0 2 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 2 1 0 0
 0 0 0 0 2 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 3 0 0 0 1 0 0 3 0 0 0 0 1 1
 0 0 0 0 1 0 0 0 0 3 1 1 0 2 3 2 0 0 1 0 1 1 1 0 3 1 0 0 0 0 0 0 2 0 0 1 0
 0 1 0 3 0 0 0 1 0 0 1 0 0 0 0 1 1 3 0 0 1 3 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 1]
accuracy 0.7341040462427746
